{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pryo.serviceAccountName" . }}
  labels:
{{ include "pryo.labels" . | nindent 4 }}
{{- end -}}
