affinity: {}
appsettings:
  enabled: true
  production: '{}'
  staging: '{}'
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: registry.itpartner.no/juselius/pryo
  tag: latest
imagePullSecrets:
- name: gitlab-registry-auth
ingress:
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    certmanager.k8s.io/cluster-issuer: ca-issuer
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  enabled: true
  hosts:
  - host: chart-example.local
    paths:
    - /
  tls:
  - hosts:
    - chart-example.local
    secretName: pryo-tls
nameOverride: ""
nodeSelector: {}
persistence:
  accessMode: ReadWriteOnce
  enabled: true
  size: 1G
  storageClass: managed-nfs-storage
podSecurityContext:
  fsGroup: 2000
replicaCount: 1
resources: {}
securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000
service:
  port: 8085
  type: ClusterIP
serviceAccount:
  create: true
  name: null
tolerations: []
